tempo:
  gateway:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
      hosts:
        - host: tempo.g8s.gaia.eu-central-1.aws.gigantic.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
          - tempo.g8s.gaia.eu-central-1.aws.gigantic.io
          secretName: tempo-ingress-cert
  storage:
    trace:
      backend: azure
      azure:
        # TODO Fill this out
