tempo:
  gateway:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
      hosts:
        - host: tempo.g8s.gaia.eu-central-1.aws.gigantic.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
          - tempo.g8s.gaia.eu-central-1.aws.gigantic.io
          secretName: tempo-ingress-cert
  storage:
    trace:
      backend: s3
      s3:
        bucket: gaia-g8s-tempo
        endpoint: s3.eu-central-1.amazonaws.com
        region: eu-central-1
