tempo:
  gateway:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-giantswarm
      hosts:
        - host: tempo.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
          - tempo.example.com
          secretName: tempo-ingress-cert
  storage:
    trace:
      backend: s3
      s3:
        bucket: # S3 bucket name
        endpoint: # S3 endpoint url
        region: # S3 region name
