version: 2.1
orbs:
  architect: giantswarm/architect@6.3.2

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push chart to control-plane-catalogs"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "tempo"
          ct_config: ".circleci/ct-config.yaml"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
