version: 2.1
orbs:
  architect: giantswarm/architect@5.5.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "tempo"
          ct_config: ".circleci/ct-config.yaml"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push chart to control-plane-catalogs"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "tempo"
          ct_config: ".circleci/ct-config.yaml"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: aws-app-collection
          app_name: "tempo"
          app_namespace: "tempo"
          app_collection_repo: "aws-app-collection"
          requires:
            - "package and push chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
